name: healthmonitorapp
description: A new Flutter project to monitor health data.

publish_to: 'none' # Remove this line if you plan to publish to the App Store.

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  health: ^3.0.0 # Add the health plugin for health data access
  provider: ^6.0.3 # Optional: Add this if you plan to use state management

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

# The following are optional if you're using assets or other resources
# assets:
#   - assets/images/
